# Generated by Django 5.2.7 on 2025-10-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_paciente_apellido_alter_paciente_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='correo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dui',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
