# Generated by Django 5.2.7 on 2025-11-09 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_cita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='clinica.medico'),
        ),
    ]
