# Generated by Django 5.2.7 on 2025-11-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_alter_servicio_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.medico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
    ]
